version: '2'

services:
  frontend:
    image: frontend
    build: .
    ports:
      - "7000:7000"
  lint:
    build:
      context: .
    command: npm run lint
  test:
    build:
      context: .
    command: npm test
